CuriosityHub/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='hub')),
]

main/urls.py
from django.urls import path

from main import views
from main.views import *

app_name = 'hub'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post-list/', PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('quizzes/', QuizListView.as_view(), name='quiz_list'),
    path('quizzes/<int:pk>/', QuizDetailView.as_view(), name='quiz_detail'),
    path('quizzes/<int:pk>/submit/', QuizSubmitView.as_view(), name='quiz_submit'),
    path('quizzes/<int:pk>/result/', QuizResultView.as_view(), name='quiz_result'),
    path('quizzes/<int:pk>/results/', QuizResultsListView.as_view(), name='quiz_results_list'),
    path('lottery/', LotteryList.as_view(), name='lottery_list'),
    path('<int:post_id>/share/', post_share, name='post_share'),
]

templates/quiz/post/detail.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <article>
        <header>
            <h3>{{ quiz.title }}</h3>
            <small>published {{ quiz.created_at }} by {{ quiz.author }}</small>
        </header>
        <section>
            <p>{{ quiz.description|linebreaks|truncatewords:50 }}</p>
        </section>
        <section>
            
            <form method="post" action="{% url 'hub:quiz_submit' quiz.id %}">
                {% csrf_token %}
                {% for question in quiz.questions.all %}
                    <fieldset class="border border-secondary rounded p-3 mb-4 bg-light">
                        <legend>{{ question.question_text|title }}</legend>

                        {% for answer in question.answers.all %}
                            <div class="input-group mb-1">
                                <div class="input-group-text">
                                    <input class="form-check-input mt-0" type="radio" id="{{ question.id }}"
                                           name="{{ question.id }}"
                                           value="{{ answer.id }}">
                                </div>
                                <input type="text" class="form-control" aria-label="{{ question.text }}"
                                       value="{{ answer.answer_text|upper }}" readonly>
                            </div>
                        {% endfor %}

                    </fieldset>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Submit Quiz</button>
            </form>
        </section>
    </article>
{% endblock %}

templates/quiz/post/list.html
{% extends 'base.html' %}

{% block content %}
    <article>
        <section>
            <div class="row d-flex gx-2 justify-content-evenly">
                {% for p in quizzes %}
                    <div class="card w-75 p-3 m-2">
                        <div class="card-body bg-light">
                            <h4 class="card-title">
                                <i class="fa-solid fa-trophy"></i>
                                <a href="{{ p.get_absolute_url }}">{{ p.title }}</a>
                            </h4>
                            <div class="card-subtitle">
                                <span>
                                    <i class="fa-solid fa-calendar-days"></i>
                                    {{ p.created_at|date }}    
                                </span><br>
                                <span>
                                    <i class="fa-solid fa-user"></i>
                                    {{ p.author }}
                                </span><br>
                                <span>
                                    <a href="{% url 'hub:quiz_results_list' p.id %}">
                                        View my related results
                                    </a>    
                                </span><br>
                                <span class="card-text">
                                    Questions : {{ p.question_count }}
                                </span>
                            </div>
                            <p class="card-text">{{ p.description|truncatewords:20 }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    </article>
{% endblock %}

templates/quiz/post/quiz_result.html
{% extends 'base.html' %}

{% block content %}
    <article>
        <header>
            <h1>Quiz Result</h1>
        </header>
        <section>
            <div>
                <p>You scored {{ score }} out of {{ total }} ({% widthratio score total 100 %}%)</p>
            </div>
        </section>
        <section>
            <div>
                <h4>Question Details</h4>
            </div>
            <div class="border border-3">
                <ul class="list-group list-group-flush list-group-numbered">
                    {% for result in results %}
                        <li class="list-group-item font-monospace">

                            <strong>Question:</strong> {{ result.question.question_text }}<br>

                            <div class="border-top border-bottom">
                                <strong>Your Answer:</strong>


                                {% if result.selected_answer %}
                                    {{ result.selected_answer.answer_text }}
                                    {% if result.selected_answer.is_correct %}
                                        <span style="color: green;">(Correct)<i class="fa-solid fa-check"></i></span>
                                    {% else %}
                                        <span style="color: red;">(Incorrect)<i class="fa-solid fa-xmark"></i></span>
                                    {% endif %}
                                {% else %}
                                    <span style="color: orange;">(No answer selected)<i
                                            class="fa-solid fa-question"></i></span>
                                {% endif %}<br>
                            </div>

                            <div class="border-top border-bottom bg-success-subtle">
                                <strong>Correct Answer:</strong> {{ result.correct_answer.answer_text }}<br>
                            </div>

                        </li>
                    {% endfor %}
                </ul>
            </div>
        </section>
        <section>
            <div class="p-2">
                <a class="btn btn-primary" href="{% url 'hub:quiz_list' %}">Back to Quizzes</a>
                <a class="btn btn-secondary" href="{% url 'hub:quiz_results_list' quiz.id %}">Quiz Results</a>
                <a class="btn btn-info" href="{% url 'hub:quiz_results_list' quiz.id %}">Related results</a>
            </div>
        </section>
    </article>
{% endblock %}

templates/quiz/post/quiz_results_list.html
{% extends 'base.html' %}

{% block content %}
    <article>
        <header><h2>All Quiz Results</h2></header>
        <section>
            <div class="card">
                <div class="card-body">
                    <div class="card-text">
                        <table class="table table-striped table-responsive caption-top">
                        <caption>All Quiz Results</caption>
                            <thead>
                            <tr>
                                <th scope="col">Quiz Name</th>
                                <th scope="col">Taken by</th>
                                <th scope="col">Score</th>
                                <th scope="col">Date</th>
                            </tr>
                            </thead>
                            <tbody class="table-group-divider">
                            {% for r in results %}
                                <tr>
                                    <th><a href="{% url 'hub:quiz_detail' r.quiz.id %}">{{ r.quiz.title }}</a></th>
                                    <td>{{ r.contestant }}</td>
                                    <td>{{ r.score }}/{{ total_questions }}</td>
                                    <td>{{ r.completed_at|date }}</td>

                                </tr>
                            {% empty %}
                                <tr>
                                    <th scope="row">0</th>
                                    <td colspan="2" class="text-danger">No Quiz Results</td>
                                    <td><a href="{% url 'hub:quiz_list' %}">Take quiz</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </article>
{% endblock %}