CuriosityHub/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='hub')),
]

main/urls.py
from django.urls import path

from main import views
from main.views import *

app_name = 'hub'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post-list/', PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('quizzes/', QuizListView.as_view(), name='quiz_list'),
    path('quizzes/<int:pk>/', QuizDetailView.as_view(), name='quiz_detail'),
    path('quizzes/<int:pk>/submit/', QuizSubmitView.as_view(), name='quiz_submit'),
    path('quizzes/<int:pk>/result/', QuizResultView.as_view(), name='quiz_result'),
    path('quizzes/<int:pk>/results/', QuizResultsListView.as_view(), name='quiz_results_list'),
    path('lottery/', LotteryList.as_view(), name='lottery_list'),
    path('<int:post_id>/share/', post_share, name='post_share'),
]

templates/blog/post/comment.html
{% extends 'base.html' %}

{% block content %}
	{% if comment %}
		<div class="card">
            <div class="card-body">
                <h1>Your comment has been noted</h1>
            </div>
        </div>
	{% else %}
		{% include 'blog/post/comment_form.html' %}
	{% endif %} 
{% endblock %}

templates/blog/post/comment_form.html
{% load crispy_forms_filters %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">Comment</h1>
            <form action="{% url 'hub:post_comment' post.id %}" method="POST">
                {{ form|crispy }}
                {% csrf_token %}
                <input class="btn btn-primary" type="submit" value="Submit"/>
            </form>
        </div>
    </div>
{% endblock %}

templates/blog/post/detail.html
{% extends 'base.html' %}

{% block content %}
    <article>
        <header>
            <h3>{{ post.title }}</h3>
            <small>published {{ post.publish }} by {{ post.author }}</small>
        </header>
        <section>
            <p>{{ post.body|linebreaks }}</p>
        </section>
        <section>
            {% with comments.count as total_comments %}
                <h3>{{ total_comments }} comment{{ total_comments|pluralize }}</h3>
            {% endwith %}
        </section>
        <section>
            {% for comment in comments %}
                <div id="comment-list">
                    <!-- Display Comments -->
                    {% for comment in post.comments.all %}
                        <div class="mb-4 p-3 border rounded bg-light">
                            <h5 class="mt-0">{{ comment.name }}</h5>
                            <p>{{ comment.body }}</p>
                            <small class="text-muted">Posted on {{ comment.created_at|date:"F j, Y" }}</small>
                        </div>
                    {% endfor %}

                </div>
            {% empty %}
                <p>No comments</p>
            {% endfor %}
            {% include 'blog/post/comment_form.html' %}
        </section>
    </article>
{% endblock %}

templates/blog/post/list.html
{% extends 'base.html' %}

{% block content %}
    <article>
        <section>
            <div class="row d-flex gx-2 justify-content-evenly">
                {% for p in posts %}
                    <div class="card w-75 p-3 m-2">
                        <div class="card-body bg-light">
                            <h4 class="card-title">
                                <i class="fa-solid fa-blog"></i>
                                <a href="{{ p.get_absolute_url }}">{{ p.title }}</a>
                            </h4>
                            <div class="card-subtitle">
                                <span>
                                   <i class="fa-solid fa-calendar-days"></i>
                                {{ p.publish|date }}
                                </span><br>
                                <span>
                                    <i class="fa-solid fa-user"></i>
                                    {{ p.author }}
                                </span>
                            </div>
                            <p class="card-text">{{ p.body|truncatewords:20 }}</p>

                            <small class="icon-link">
                                <i class="fa-solid fa-comment"></i>
                                Comments: {{ p.comment_count }}
                            </small>
                            <div class="vr icon-link"></div>
                            <small>
                                <a class="icon-link" href="{% url 'hub:post_share' p.id %}">
                                    <i class="fa-solid fa-envelope"></i>
                                    Email
                                </a>
                            </small>
                            <div class="vr icon-link"></div>
                            <small>
                                <a class="icon-link" href="whatsapp://send?text={{ request.build_absolute_uri }}{{ p.get_absolute_url }}" data-action="share/whatsapp/share">
                                    <i class="fa-brands fa-whatsapp"></i>
                                    Whatsapp
                                </a>
                            </small>

                        </div>
                    </div>
                {% endfor %}
            </div>
            {% include "pagination.html" with page=page_obj %}
        </section>
    </article>
{% endblock %}

templates/blog/post/share.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}


{% block content %}
    <article>
        <header>Sharing a post!</header>
        <section>
            {% if sent %}
                <div class="card">
                    <div class="card-body">
                        <h1>Email has been successfully sent</h1>
                        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data }}</p>
                    </div>
                </div>
            {% else %}
                <div class="card">
                    <div class="card-body">
                        <h1>Share "{{ post.title }}" by email</h1>
                        <form method="post">
                            {{ form|crispy }}
                            {% csrf_token %}
                            <input type="submit" class="btn btn-primary" value="Send" />
                        </form>
                    </div>
                </div>

            {% endif %}
        </section>
    </article>
{% endblock %}