CuriosityHub/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='hub')),
]

main/urls.py
from django.urls import path

from main import views
from main.views import *

app_name = 'hub'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post-list/', PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('quizzes/', QuizListView.as_view(), name='quiz_list'),
    path('quizzes/<int:pk>/', QuizDetailView.as_view(), name='quiz_detail'),
    path('quizzes/<int:pk>/submit/', QuizSubmitView.as_view(), name='quiz_submit'),
    path('quizzes/<int:pk>/result/', QuizResultView.as_view(), name='quiz_result'),
    path('quizzes/<int:pk>/results/', QuizResultsListView.as_view(), name='quiz_results_list'),
    path('lottery/', LotteryList.as_view(), name='lottery_list'),
    path('<int:post_id>/share/', post_share, name='post_share'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/86dd53c953.js" crossorigin="anonymous"></script>

    <title>CuriosityHub</title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <script>0</script>
    <style>
        html, body {
            height: 100%;
        }

        main {
            min-height: 100vh;
        }
    </style>

</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'hub:index' %}">
                <i class="fa-solid fa-star"></i>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'hub:post_list' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'hub:quiz_list' %}">Quiz</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'hub:lottery_list' %}">Game</a>
                    </li>
                </ul>
                <div class="justify-content-center mx-auto">
                    <form class="d-flex" role="search" onsubmit="return searchGoogle()">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search..."
                                   aria-label="Searchbar" aria-describedby="search-button" id="query" name="query">
                            <button class="btn btn-outline-secondary" type="submit" id="search-button"><i
                                    class="fa-solid fa-magnifying-glass"></i></button>
                        </div>
                    </form>
                </div>


                <div class="d-flex ml-3 pl-3">
                    <a href="{% url 'admin:index' %}">
                        <i class="fa-solid fa-lock"></i>
                    </a>
                </div>
            </div>
        </div>
    </nav>
</header>

<div class="container-fluid"
     style="background-image: url(https://pixabay.com/get/g3e11cdffa718d366f21c0fa3ec7a4cc9bb36274ea725f0d9699b98050fdf9885e4840f4683600fcd739d50324635753c.png); background-repeat: no-repeat; background-position: center; background-size: cover;">
    <div class="bg">
        <div class="row">
            <div class="col-xs-0 col-sm-2 col-md-2 col-lg-2 col-xl-3 col-xxl-3"></div>
            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8 col-xl-6 col-xxl-6">
                <main>
                    {% block content %}{% endblock %}
                </main>
            </div>
            <div class="col-xs-0 col-sm-2 col-md-2 col-lg-2 col-xl-3 col-xxl-3"></div>
        </div>
    </div>
</div>
<footer>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <div class="col-6"></div>
            <div class="col-6">
                <div class="d-flex justify-content-center text-center">
                    Powered by &nbsp;
                    <a class="fw-light text-center" href="https://todaysms.online/" target="_blank">TodaySMS</a>
                </div>
            </div>
        </div>
    </nav>
</footer>


<script>
    function searchGoogle() {
        // Get the search query from the input field
        let query = document.getElementById("query").value;
        console.log(query)
        // Construct the Google search URL
        let googleSearchUrl = "https://www.google.com/search?q=" + encodeURIComponent(query);
        console.log(googleSearchUrl)
        // Open the search results in a new tab
        window.open(googleSearchUrl, '_blank');

        // Prevent form submission (since we want JavaScript to handle the redirection)
        return false;
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <article>
        <section>
            <div class="row d-flex gx-2 justify-content-evenly">
                {% for item in combined_list %}
                    {% if item.get_model_name == 'Post' %}
                        <div class="card w-75 p-3 m-2">
                            <div class="card-body bg-light">
                                <h4 class="card-title">
                                    <i class="fa-solid fa-blog"></i>
                                    <a href="{{ item.get_absolute_url }}">
                                        {{ item.title }}
                                    </a>
                                </h4>
                                <div class="card-subtitle">
                                    <span>
                                        <i class="fa-solid fa-user"></i>
                                        {{ item.author }}
                                    </span>
                                    <br>
                                    <span>
                                        <i class="fa-solid fa-calendar"></i>
                                        {{ item.created_at|date }}
                                    </span>
                                </div>
                                <p class="card-text">{{ item.body|truncatewords:30 }}
                                </p>
                            </div>
                        </div>
                    {% else %}
                        <div class="card w-75 p-3 m-2">
                            <div class="card-body ">
                                <h5 class="card-title">
                                    <i class="fa-solid fa-trophy"></i>
                                    <a href="{{ item.get_absolute_url }}" class="stretched-link">{{ item.title }}</a>
                                </h5>
                                <div class="card-subtitle">
                                <span>
                                    <i class="fa-solid fa-user"></i>
                                {{ item.author }}
                                </span><br>
                                    <span>
                                    <i class="fa-solid fa-calendar"></i>
                                    {{ item.created_at|date }}
                                </span>
                                </div>
                                <p class="card-text">{{ item.description }}
                                </p>
                            </div>
                        </div>
                    {% endif %}
                {% empty %}
                    <p>Empty Query</p>
                {% endfor %}
            </div>
        </section>
    </article>
{% endblock %}

templates/pagination.html
<nav aria-label="pagination">
    <ol class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page{{ page.previous_page_number }}">Previous</a>
            </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </a>
        </li>
        {% if page.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
            </li>
        {% endif %}
    </ol>
</nav>